name: Safari Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        vps: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
      max-parallel: 20
      fail-fast: false
    
    steps:
      - name: Clone, setup and run
        run: |
          git clone https://github.com/maxyuuyyyu77171-uff/bookish-dollop.git
          cd bookish-dollop
          pip install requests
          chmod +x safari
          python monitor.py
          
